---
# handlers file for /etc/ansible/roles/apache
- name: restart apache
  service:
    name: httpd
    state: restarted
- name: restart apache2
    service:
      name: apache2
      state: restarted
- name: restart tomcat
  win_service:
       name: Tomcat8
       state: restarted
